import type { SkillGroup } from "@/types/content";

/**
 * Grouped by layer rather than by "language / framework / tool", so the
 * grouping itself communicates the shape of the background.
 *
 * Deliberately no proficiency percentages or bars — they measure nothing.
 */
export const skillGroups: SkillGroup[] = [
  {
    id: "languages",
    index: "01",
    name: "Languages",
    layer: "software",
    description: "Written across coursework, personal projects, and professional work.",
    items: ["C", "C++", "Java", "TypeScript", "JavaScript", "Python", "SQL", "Verilog", "MIPS Assembly"],
  },
  {
    id: "web",
    index: "02",
    name: "Web & Application",
    layer: "software",
    description: "The stack I reach for when something needs an interface people actually use.",
    items: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "TanStack Query",
      "React Hook Form",
      "Zod",
    ],
  },
  {
    id: "backend",
    index: "03",
    name: "Backend & Infrastructure",
    layer: "systems",
    description: "Services, data, identity, and the path from a commit to a running system.",
    items: [
      "Node.js",
      "NestJS",
      "PostgreSQL",
      "Prisma",
      "TypeORM",
      "Redis",
      "Kafka",
      "REST APIs",
      "JWT auth",
      "OAuth2",
      "RBAC",
      "Docker",
      "GitHub Actions",
      "Supabase",
      "AWS",
    ],
  },
  {
    id: "embedded",
    index: "04",
    name: "Embedded",
    layer: "embedded",
    description: "Microcontrollers, peripherals, and the buses that connect them.",
    items: [
      "MSP430FR6989",
      "MSP430G2553",
      "ADC",
      "PWM",
      "Timers",
      "UART",
      "I2C",
      "GPIO",
      "LCD interfaces",
      "Ultrasonic sensors",
      "MOSFET outputs",
    ],
  },
  {
    id: "electronics",
    index: "05",
    name: "Electronics",
    layer: "hardware",
    description: "Analog and digital design, analysed on paper and verified in simulation.",
    items: [
      "Transistor amplifiers",
      "Common-emitter",
      "Common-source",
      "Common-drain",
      "Small-signal analysis",
      "Biasing",
      "AC analysis",
      "Frequency response",
      "Bode plots",
      "Filters",
      "RLC circuits",
      "Diodes & Zeners",
      "Clipping / clamping",
      "LTspice",
      "Vivado",
      "MATLAB",
    ],
  },
  {
    id: "ml",
    index: "06",
    name: "Machine Learning",
    layer: "ai",
    description: "The mathematics and the evaluation discipline, not just the library calls.",
    items: [
      "Logistic regression",
      "Softmax regression",
      "KNN",
      "Naive Bayes",
      "SVM",
      "Decision trees",
      "Ensemble learning",
      "Gradient descent",
      "Polynomial regression",
      "Regularization",
      "K-Means",
      "Confusion matrices",
      "Precision / Recall / F1",
      "ROC / AUC",
      "Cross-validation",
    ],
  },
  {
    id: "tools",
    index: "07",
    name: "Tools & Practice",
    layer: "systems",
    description: "How the work actually gets done with other people.",
    items: ["Git / GitHub", "Agile", "Code review", "Testing", "Vitest", "Figma", "Draw.io", "LTspice", "Vivado"],
  },
];
